# Generated by Django 4.2.7 on 2025-08-31 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0003_shipment_shipmentoffer_profile_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('basic', 'Basic - 5% popust'), ('premium', 'Premium - 10% popust + odloženo plaćanje'), ('enterprise', 'Enterprise - 15% popust + mesečna faktura')], max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('deferred_payment_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RSD', max_length=3)),
                ('status', models.CharField(choices=[('reserved', 'Rezervisano'), ('captured', 'Naplaćeno'), ('released', 'Oslobođeno'), ('failed', 'Neuspešno')], default='reserved', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(default='card', max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reservation', to='transport.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='InstantDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('pickup_coordinates', models.CharField(blank=True, max_length=50)),
                ('delivery_coordinates', models.CharField(blank=True, max_length=50)),
                ('delivery_type', models.CharField(choices=[('express', 'Express (do 1h)'), ('same_day', 'Isti dan'), ('scheduled', 'Zakazano')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Na čekanju'), ('accepted', 'Prihvaćeno'), ('pickup', 'Preuzimanje'), ('in_transit', 'U tranzitu'), ('delivered', 'Dostavljeno'), ('cancelled', 'Otkazano')], default='pending', max_length=20)),
                ('item_description', models.TextField()),
                ('estimated_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('special_instructions', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField()),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instant_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('restaurant_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('customer_phone', models.CharField(max_length=20)),
                ('items', models.JSONField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=200.0, max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Na čekanju'), ('confirmed', 'Potvrđeno'), ('preparing', 'Priprema se'), ('ready', 'Spremno za preuzimanje'), ('pickup', 'Preuzeto'), ('delivered', 'Dostavljeno'), ('cancelled', 'Otkazano')], default='pending', max_length=20)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_preparation', models.IntegerField(default=30)),
                ('estimated_delivery', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_deliveries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(default=0.0)),
                ('speed', models.FloatField(default=0.0)),
                ('heading', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='transport.instantdelivery')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
                ('food_delivery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='transport.fooddelivery')),
            ],
        ),
    ]
