# Generated by Django 4.2.7 on 2025-09-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_tour_model_update'),
    ]

    operations = [
    ]
