# Generated by Django 4.2.7 on 2025-09-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20250904_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='loading_height',
            field=models.IntegerField(default=250, help_text='Visina utovarnog dela u cm'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transport_license',
            field=models.CharField(blank=True, help_text='Broj dozvole za prevoz tereta', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_brand',
            field=models.CharField(choices=[('mercedes', 'Mercedes-Benz'), ('volvo', 'Volvo'), ('scania', 'Scania'), ('man', 'MAN'), ('daf', 'DAF'), ('iveco', 'Iveco'), ('renault', 'Renault Trucks'), ('ford', 'Ford'), ('isuzu', 'Isuzu'), ('fiat', 'Fiat')], default='mercedes', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_color',
            field=models.CharField(choices=[('bela', 'Bela'), ('crna', 'Crna'), ('siva', 'Siva'), ('plava', 'Plava'), ('crvena', 'Crvena'), ('zelena', 'Zelena'), ('zuta', 'Žuta'), ('narandzasta', 'Narandžasta')], default='bela', max_length=20),
        ),
    ]
