# Generated by Django 4.2.7 on 2025-09-05 19:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0007_vehicle_loading_height_vehicle_transport_license_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tour',
        ),
        migrations.AddField(
            model_name='notification',
            name='sound_file',
            field=models.CharField(default='ping.mp3', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CenaPoKilometrazi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_paleta', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cena_do_200km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cena_preko_200km', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Cena po kilometraži',
                'verbose_name_plural': 'Cene po kilometraži',
                'unique_together': {('broj_paleta',)},
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tezina', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('broj_paleta', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('opis_tereta', models.TextField(blank=True)),
                ('polazna_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('polazna_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('polazna_adresa', models.CharField(max_length=255)),
                ('odredisna_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('odredisna_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('odredisna_adresa', models.CharField(max_length=255)),
                ('udaljenost_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cena_za_posiljaoce', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cena_za_prevoznika', models.DecimalField(decimal_places=2, max_digits=10)),
                ('app_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('eko_ambalaza', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Na čekanju'), ('reserved', 'Rezervisano'), ('assigned', 'Dodeljeno prevozniku'), ('in_transit', 'U transportu'), ('delivered', 'Isporučeno'), ('paid', 'Plaćeno')], default='pending', max_length=20)),
                ('kreiran', models.DateTimeField(auto_now_add=True)),
                ('isporucen', models.DateTimeField(blank=True, null=True)),
                ('posiljilac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiljke', to=settings.AUTH_USER_MODEL)),
                ('prevoznik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teretni_poslovi', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tereti', to='transport.tour')),
            ],
        ),
    ]
