# Generated by Django 4.2.7 on 2025-09-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='maticni_broj',
            field=models.CharField(blank=True, max_length=20, verbose_name='Matični broj'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pib',
            field=models.CharField(blank=True, max_length=20, verbose_name='PIB'),
        ),
    ]
