# Generated by Django 4.2.7 on 2025-09-20 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0009_profile_maticni_broj_profile_pib'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_offer', 'Nova ponuda'), ('offer_accepted', 'Ponuda prihvaćena'), ('offer_rejected', 'Ponuda odbijena'), ('tour_confirmed', 'Tura potvrđena'), ('pickup_confirmed', 'Preuzimanje potvrđeno'), ('delivery_confirmed', 'Isporuka potvrđena'), ('new_message', 'Nova poruka'), ('cargo', 'Nova pošiljka'), ('payment', 'Plaćanje'), ('tour_started', 'Tura pokrenuta'), ('tour_completed', 'Tura završena')], default='new_offer', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.shipment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.tour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
