# Generated by Django 4.2.7 on 2025-09-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sound_file',
        ),
    ]
