# Generated by Django 4.2.7 on 2025-10-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_remove_notification_sound_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='drivers_license',
            field=models.CharField(blank=True, help_text='Broj vozačke dozvole', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_years',
            field=models.CharField(blank=True, help_text='Godine iskustva (0-2, 2-5, 5-10, 10+)', max_length=10),
        ),
    ]
