# Generated by Django 4.2.7 on 2025-10-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_profile_drivers_license_profile_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=34, verbose_name='Broj računa'),
        ),
    ]
